name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  {% raw -%}
  group: ${{ github.workflow }}-${{ github.ref_name }}
  {%- endraw %}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
      - uses: golangci/golangci-lint-action@v6
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
      - run: go test -v ./...
  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
  {% raw -%}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MATTERMOST_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK }}
  {%- endraw %}
